using OpenAI.Chat;

namespace ChatGPTService.Utilities;

public static class ChatTools
{
	public static ChatTool ReadFromCalendarTodayTool = ChatTool.CreateFunctionTool(
		nameof(ChatToolsFunctions.ReadFromCalendarTodayAsync),
		"Get the user's events from their calendar for today"
	);

	public static ChatTool AddToCalendarTool = ChatTool.CreateFunctionTool(
		nameof(ChatToolsFunctions.AddToCalendarAsync),
		"Add an event to the Events databasee",
		BinaryData.FromString(
			"""
			{
			    "type": "object",
			    "properties": {
			        "datetime": {
			            "type": "string",
			            "format": "date-time",
			            "description": "Date and time of the event. Must be a valid ISO 8601 date-time string."
			        },
			        "name": {
			            "type": "string",
			            "description": "Name of the event. A brief, descriptive title."
			        },
			        "location": {
			            "type": "string",
			            "description": "Location of the event. Can be an address or virtual meeting link."
			        },
			        "notes": {
			            "type": "string",
			            "description": "Additional notes or details about the event."
			        },
					"IsRecurring": {
			            "type": "boolean",
			            "description": "Indicates if the event is recurring."
			        },
					"RecurrencePattern": {
			            "type": "string",
			            "description": "Pattern for recurring events. Required if IsRecurring is true."
			        },
			        "notification": {
			            "type": "object",
			            "properties": {
			                "Message": {
			                    "type": "string",
			                    "description": "Notification message to be sent generated by chatgpt."
			                },
			                "SentAt": {
			                    "type": "string",
			                    "format": "date-time",
			                    "description": "Timestamp when the notification should be sent. Required and must be a valid ISO 8601 date-time string."
			                }
			            },
			            "required": ["Message", "SentAt"]
			        }
			    },
			    "required": ["datetime", "name", "notes", "IsRecurring", "location"]
			}
			"""
		)
	);

	public static ChatTool RemoveFromCalendarTool = ChatTool.CreateFunctionTool(
		nameof(ChatToolsFunctions.RemoveFromCalendarAsync),
		"Remove an event from the Events database",
		BinaryData.FromString(
			"""
			{
			    "type": "object",
			    "properties": {
			        "SearchTerm": {
			            "type": "string",
			            "description": "A string representing the search term. This value must match the expected format for the field being searched. For date fields (e.g., StartTime, EndTime, CreatedAt), provide a valid ISO 8601 date-time string."
			        },
			        "SearchColumn": {
			            "type": "string",
			            "description": "The column to search in. Must be one of the following: 'Title', 'Description', 'StartTime', 'EndTime', 'Location', or 'CreatedAt'."
			        }
			    },
				"required": ["SearchTerm", "SearchColumn"]
			}
			"""
		)
	);

	public static ChatTool UpdateCalendarEventTool = ChatTool.CreateFunctionTool(
		nameof(ChatToolsFunctions.UpdateCalendarEventAsync),
		"Update and amend the details of an existing event in the Events database",
		BinaryData.FromString(
			"""
			{
			    "type": "object",
			    "properties": {
			        "SearchTerm": {
			            "type": "string",
			            "description": "A string representing the search term. This value must match the expected format for the field being searched. For date fields (e.g., StartTime, EndTime, CreatedAt), provide a valid ISO 8601 date-time string."
			        },
			        "SearchColumn": {
			            "type": "string",
			            "description": "The column to search in. Must be one of the following: 'Title', 'Description', 'StartTime', 'EndTime', 'Location', or 'CreatedAt'."
			        },
			        "StartTime": {
			            "type": "string",
			            "format": "date-time",
			            "description": "New start date time of event. Must be a valid ISO 8601 date-time string."
			        },
					"EndTime": {
			            "type": "string",
			            "format": "date-time",
			            "description": "New end date time of event. Must be a valid ISO 8601 date-time string."
			        },
			        "Name": {
			            "type": "string",
			            "description": "New name of the event."
			        },
					"Description": {
			            "type": "string",
			            "description": "New name of the event."
			        },
					"IsRecurring": {
						"type": "boolean",
						"description": "if the event is recurring"
			        },
					"RecurrencePattern": {
			            "type": "string",
			            "description": "Pattern for recurring events. Required if IsRecurring is true."
			        },
					"Location": {
			            "type": "string",
			            "description": "New location of the event."
			        }
			    },
				"required": ["SearchTerm", "SearchColumn"]
			}
			"""
		)
	);

	public static ChatTool GetEventDetailsTool = ChatTool.CreateFunctionTool(
		nameof(ChatToolsFunctions.GetEventDetailsAsync),
		"Retrieve details of an event from the calendar based on a search term",
		BinaryData.FromString(
			"""
			{
			    "type": "object",
			    "properties": {
			        "SearchTerm": {
			            "type": "string",
			            "description": "A string representing the search term. This value must match the expected format for the field being searched. For date fields (e.g., StartTime, EndTime, CreatedAt), provide a valid ISO 8601 date-time string."
			        },
			        "SearchColumn": {
			            "type": "string",
			            "description": "The column to search in. Must be one of the following: 'Title', 'Description', 'StartTime', 'EndTime', 'Location', or 'CreatedAt'."
			        }
			    },
				"required": ["SearchTerm", "SearchColumn"]
			}
			"""
		)
	);

	public static ChatTool CreateTaskTool = ChatTool.CreateFunctionTool(
		nameof(ChatToolsFunctions.CreateTaskAsync),
		"Add a task to the task list",
		BinaryData.FromString(
			"""
			{
			    "type": "object",
			    "properties": {
			        "name": {
			            "type": "string",
			            "description": "Title of the task."
			        },
			        "notes": {
			            "type": "string",
			            "description": "Additional notes or description for the task."
			        },
			        "priority": {
			            "type": "string",
			            "description": "Priority level of the task."
			        },
					"dueDate": {
			            "type": "string",
			            "description": "Due date of the task. Must be a valid ISO 8601 date-time string."
			        },
					  "notification": {
			            "type": "object",
			            "properties": {
			                "Message": {
			                    "type": "string",
			                    "description": "Notification message to be sent."
			                },
			                "SentAt": {
			                    "type": "string",
			                    "format": "date-time",
			                    "description": "Timestamp when the notification should be sent. Required and must be a valid ISO 8601 date-time string."
			                }
			            },
			            "required": ["Message", "SentAt"]
			        }
			    },
			    "required": ["name", "notes"]
			}
			"""
		)
	);
}
